- name: Play level variables
  hosts: all
  vars:
    URL: play.example.com
    a: 10000
  vars_files:
    - 02-sample-vars
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: "{{URL}}"
    - name: Task2
      ansible.builtin.debug:
        msg: "{{a}}"
- name: vars from file
  hosts: all
  vars_files:
    - 02-sample-vars
  tasks:
    - name: Var from file
      ansible.builtin.debug:
        msg: "{{URL}}"