- name: Play level variables
  hosts: all
  vars:
    URL: play.example.com
    a: 10000
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: "{{URL}}"
    - name: Task2
      ansible.builtin.debug:
        msg: "{{a}}"

- name: Play for vars from file
  hosts: all
  vars_files:
    - 02-sample-vars.yml
  tasks:
    - name: Var from file
      ansible.builtin.debug:
        msg: "{{URL}}"

- name: Play for task level vars
  hosts: all
  tasks:
    - name: URL1 var of task1
      ansible.builtin.debug:
        msg: "{{URL}"
      vars:
        URL: one.example.com
    - name: URL2 var of task2
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: second.example.com