- name: demo on condition
  hosts: localhost
  vars:
    abc: ABC
    val: 50
    apply: true
  tasks:
    - name: condition with string
      debug:
        msg: "abc = ABC "
      when: abc == "ABC"
    - name: condition with string
      debug:
        msg: "abc = abc "
      when: abc == "abc"

    - name: condition with numbers
      debug:
        msg: "  greater than or equal {{val}}"
      when: val | int > 50
    - name: condition with numbers
      debug:
        msg: "  less than {{val}}"
      when: val | int < 50

    - name: condition on boolean
      debug:
        msg: "applying"
      when: apply | bool

    - name: multiple conditions
      debug:
        msg: "abc==ABC and val==50"
      when: abc == "ABC" and val == 50

