- name: demo on condition
  hosts: localhost
  vars:
    abc: ABC
    val: 50
  tasks:
    - name: condition with string
      debug:
        msg: "abc = ABC "
      when: abc == "ABC"
    - name: condition with string
      debug:
        msg: "abc = abc "
      when: abc == "abc"

    - name: condition with numbers
      debug:
        msg: " 50 greater than or equal"
      when: val | int > 50
    - name: condition with numbers
      debug:
        msg: " 50 less than "
      when: val | int < 50