- name: demo on condition
  hosts: localhost
  vars:
    abc: ABC
    val: 50
  tasks:
    - name: condition with string
      debug:
        msg: "abc = ABC "
      when: abc == "ABC"
    - name: condition with string
      debug:
        msg: "abc = abc "
      when: abc == "abc"

    - name: condition with numbers
      debug:
        msg: "  greater than or equal {{val}}"
      when: val | int > 50
    - name: condition with numbers
      debug:
        msg: "  less than {{val}}"
      when: val | int < 50