- name: demo on loop
  hosts: localhost
  vars:
    fruits: [ "Apple","Banana","Mango","Pineaple"]
  tasks:
    - name: print fruit name
      loop: "{{fruits}}"
      debug:
        msg: "{{item}}"

