- name: Install Maven Service
  ansible.builtin.yum:
    name:
      - maven
    state: installed


- name: Application user setup and download app file
  import_tasks: app-user-setup.yml

- name: Compile Code
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop


- name: Setup service and Start service
  import_tasks: systemd.yml

